### ISSUE TITLE
Finalize Client APIs, CLI

### ISSUE THREAD

**Issue by spencercorwin** [neo-one-suite/neo-one#2218]
- [x] Finalize `client-common` crypto module
- [x] Finalize `client-full-core` package
- [x] Finalize `client-core` package
- [x] Finalize `client` package
- [x] Finalize `client-full` package
- [x] Finalize `client-switch` package
- [x] Finalize `cli` package
- [x] Finalize `cli-common` package
- [x] Finalize `cli-common-node` package

UserAccountProvider layer
- [x] Finalize `invokeClaim` in `client-common/src/types.ts`, `__invokeClaim` in `Client.ts`, `invokeClaim` in UAPB
- [x] Finalize `getSystemFee` and `checkSystemFees` in UAPB (see #2098)
- [x] Finalize `getTransactionOptions` in UAPB. See C# code
- [x] `executeInvokeMethod` and `executeInvokeScript` in LUAP. See `invokeScript` and `invokeFunction` in `neo-modules` (see #2098, #2206)
- [x] Finalize `executeTransfer` in LUAP. Should be able to transfer any "asset"

Others
- [x] Finalize `RawNotification`/`NewRawNotification` types in `client-common`
- [x] Finalize `RawCallReceipt` type in Client, `convertCallReceipt` method, `CallReceipt` type in Node
- [x] Finalize/fix `RawStackItem` type, especially `RawStackItem.value` type
- [x] Finalize `convertStackItem` method in `convert.ts`. Needs to convert Interop and Struct stack items? Check `StackItemJSON` type. Also `stackItemToJSON` method (see #2189)
- [x] Finalize `ContractMethodDescript.offset` and `ContractMethodDescriptClient.offset` in `args.ts` and `nep5.ts`
- [x] Check decimals and offset, and script/hash in nep5.ts and related type definitions
- [ ] #2098
- [ ] #2113
