### ISSUE TITLE
Consensus Checklist

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#2227]
Things we need before we can call consensus 'done':

- [x] Ability to quickly form and sign a transaction
- [x] Ability to use 1 validator which we have the private key information for to bootstrap a list of additional wallets with funds.
- [x] verify that we can use these bootstrapped wallets to transfer funds between themselves.

**Comment by danwbyrne** [comment]
#2235
